default['delivery']['knife']['node_name'] = 'v-vasundhara'
default['delivery']['knife']['chef_server_url'] = 'https://chef-server.delivery.chef.co/organizations/chef'
default['delivery']['knife']['client_key_path'] = '/tmp/client.pem'
default['delivery']['azure']['linux_vmname'] = 'linux-vm-test1'
default['delivery']['azurerm']['linux_vmname'] = 'pipelinuxarm'
default['delivery']['azure']['windows_vmname'] = 'win-vm-test1'
default['delivery']['azurerm']['windows_vmname'] = 'pipewinarm'