default['delivery']['knife']['node_name'] = 'cheftestaccount2015'
default['delivery']['knife']['chef_server_url'] = 'https://api.chef.io/organizations/tstorgnztn'
default['delivery']['knife']['client_key_path'] = '/tmp/client.pem'
default['delivery']['azure']['linux_vmname'] = 'linux-vm-test1'
default['delivery']['azurerm']['linux_vmname'] = 'armlinux-vm-test1'
default['delivery']['azure']['windows_vmname'] = 'win-vm-test1'
default['delivery']['azurerm']['windows_vmname'] = 'armwin-vm-test1'